easy_admin:
    site_name: 'Le Plongeur Masqué de Trévoux'
    formats:
        number: '%0.02f €'
    design:
        brand_color: '#3c8e91'
        assets:
            css: ['css/custom_backend.css']
        menu:
            - { label: 'Membres' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Inscription', icon: 'check-circle' }
            - { entity: 'InscriptionStatus', icon: 'check-circle' }
            - { entity: 'Office', icon: 'group' }
            - { label: 'Les sorties' }
            - { entity: 'Trip', icon: 'plane' }
            - { entity: 'Type', icon: 'ship' }
            - { entity: 'Participant', icon: 'group' }
            - { label: 'Adhésion / Assurance' }
            - { entity: 'AdhesionPrice', icon: 'pencil' }
            - { entity: 'Payment', icon: 'credit-card' }
            - { entity: 'Insurance', icon: 'balance-scale' }
            - { label: 'Autres' }
            - { entity: 'Picture', icon: 'photo' }
            - { entity: 'Level', icon: 'life-saver' }
            - { entity: 'Document', icon: 'info' }
            - { label: 'Retour au site', route: 'pmtindex', icon: 'reply'}
    list:
        max_results: 20

    entities:
        User:
            translation_domain: 'messages'
            class: App\Entity\User
            label: 'Adhérents au PMT'
            list:
                actions: ['edit', 'search', 'delete', 'show']
                title: 'Liste des adhérents au PMT'
                fields:
                    - { property: 'imageFile', template: 'vich_uploader_image.html.twig' }
                    - { property: 'firstname',  type: 'text' }
                    - { property: 'lastname',  type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'home_phone', type: 'tel' }
                    - { property: 'mobile_phone', type: 'tel' }
                    - { property: 'birthday', type: 'date', format: 'd/m/Y'}
                    - address
                    - { property: 'zip_code',  type: 'text' }
                    - city
                    - level
                    - comment
                    - office
                    - { property: 'is_admin',  type: 'boolean' }
                    - { property: 'is_monitor',  type: 'boolean' }
                    - { property: 'is_swim',  type: 'boolean' }
                    - { property: 'is_diver',  type: 'boolean' }
                    - { property: 'is_handi',  type: 'boolean' }
            search:
                fields:
                    - property: 'firstname'
                    - property: 'lastname'
                    - property: 'email'
                    - property: 'homePhone'
                    - property: 'mobilePhone'
                    - property: 'birthday'
                    - property: 'address'
                    - property: 'zipCode'
                    - property: 'city'
                    - property: 'comment'
                    - property: 'level.name'
            new:
                title: 'Créer un adhérent'
                fields:
                    - { property: 'imageFile', type: 'vich_image'}
                    - { property: 'firstname',  type: 'text' }
                    - { property: 'lastname',  type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'home_phone', type: 'tel' }
                    - { property: 'mobile_phone', type: 'tel' }
                    - { property: 'birthday', type: 'App\Form\DatePicker'}
                    - address
                    - { property: 'zip_code',  type: 'text' }
                    - city
                    - level
                    - comment
                    - office
                    - { property: 'is_admin',  type: 'checkbox' }
                    - { property: 'is_monitor',  type: 'checkbox' }
                    - { property: 'is_swim',  type: 'checkbox' }
                    - { property: 'is_diver',  type: 'checkbox' }
                    - { property: 'is_handi',  type: 'checkbox' }
            edit:
                title: 'Editer un adhérent'
                fields:
                    - { property: 'imageFile', type: 'vich_image'}
                    - { property: 'firstname',  type: 'text' }
                    - { property: 'lastname',  type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'home_phone', type: 'tel' }
                    - { property: 'mobile_phone', type: 'tel' }
                    - { property: 'birthday', type: 'App\Form\DatePicker'}
                    - address
                    - { property: 'zip_code',  type: 'text' }
                    - city
                    - level
                    - comment
                    - office
                    - { property: 'is_admin',  type: 'checkbox' }
                    - { property: 'is_monitor',  type: 'checkbox' }
                    - { property: 'is_swim',  type: 'checkbox' }
                    - { property: 'is_diver',  type: 'checkbox' }
                    - { property: 'is_handi',  type: 'checkbox' }
            show:
                title: "Profil de l'adhérent"
                fields:
                    - { property: 'imageFile', type: 'image' , template: 'vich_uploader_image.html.twig' }
                    - firstname
                    - lastname
                    - { property: 'email', type: 'email' }
                    - { property: 'home_phone', type: 'tel' }
                    - { property: 'mobile_phone', type: 'tel' }
                    - birthday
                    - address
                    - { property: 'zip_code', type: 'text'}
                    - city
                    - level
                    - comment
                    - office
                    - { property: 'is_admin',  type: 'boolean' }
                    - { property: 'is_monitor',  type: 'boolean' }
                    - { property: 'is_swim',  type: 'boolean' }
                    - { property: 'is_diver',  type: 'boolean' }
                    - { property: 'is_handi',  type: 'boolean' }
        Office:
            class: App\Entity\Office
            label: 'Fonctions du bureau'
            list:
                title: 'Fonctions des membres du bureau'
                fields:
                    - name
            form:
                title: 'Editer un rôle'
                fields:
                    - name
        Level:
            class: App\Entity\Level
            label: 'Niveaux de plongée'
            list:
                title: 'Niveaux de plongée'
                fields:
                    - name
            form:
                title: 'Editer un niveaux de plongée'
                fields:
                    - name

        Trip:
          class: App\Entity\Trip
          label: 'Sorties'
          list:
            actions: ['edit', 'search', 'delete', 'show']
            title: 'Liste des sorties'
            fields:
              - { property: 'imageFile', template: 'vich_uploader_image.html.twig' }
              - name
              - location
              - { property: 'price', number: '%0.02f €'}
              - typeTrip
              - { property: 'date_start', type: 'datetime' }
              - { property: 'date_end', type: 'datetime' }
              - description
              - nb_diver
              - nb_monitor
          form:
            title: 'Editer une sortie'
            fields:
              - { property: 'imageFile', type: 'vich_image'}
              - name
              - typeTrip
              - location
              - { property: 'price', number: '%0.02f €'}
              - { property: 'date_start', type: 'datetime' }
              - { property: 'date_end', type: 'datetime' }
              - description
              - { property: 'nb_diver', type: 'text' }
              - { property: 'nb_monitor', type: 'text' }

          show:
            title: 'Liste des sorties'
            fields:
              - { property: 'imageFile', template: 'vich_uploader_image.html.twig' }
              - name
              - location
              - { property: 'price', number: '%0.02f €'}
              - typeTrip
              - { property: 'date_start', type: 'datetime' }
              - { property: 'date_end', type: 'datetime' }
              - description
              - { property: 'nb_diver', type: 'text' }
              - { property: 'nb_monitor', type: 'text' }
        Type:
            class: App\Entity\TypeTrip
            label: 'Type de sortie'
            list:
                title: 'Type de sortie'
                fields:
                    - name
            form:
                title: 'Editer un type de sortie'
                fields:
                    - name
        Picture:
            class: App\Entity\Picture
            label: 'Photos'
            actions: ['search', 'delete', 'show']
            list:
                title: 'Liste des photos'
                fields:
                    - { property: 'name', type: 'text'}

                    - { property: 'imageFile', template: 'vich_uploader_image.html.twig'}

                    - comments
            show:
                title: 'Liste des photos'
                fields:
                    - { property: 'name', type: 'text'}
                    - { property: 'imageFile', type: 'image', base_path: '%app.path.product_images%' }
                    - comments
            form:
                title: 'Ajouter / Modifier une photo'
                fields:
                    - { property: 'imageFile', type: 'vich_image'}
                    - comments
        Payment:
            translation_domain: 'messages'
            class: App\Entity\Payment
            label: 'Type de paiement'
            list:
                title: 'Type de paiement'
                fields:
                    - type_payment
            form:
                title: 'Ajouter / Modifier un type de paiement'
                fields:
                    - { property: 'type_payment', type: 'text'}
        Participant:
            class: App\Entity\Participant
            label: 'Participants aux sorties'
            list:
                title: 'Liste des participants aux sorties'
                fields:
                    - user
                    - trip
                    - nb_companion
                    - { property: 'payment', type: 'text'}
                    - status
                    - inscription_status
                    - comment
            search:
                fields:
                    - property: 'user.firstname'
                    - property: 'user.lastname'
                    - property: 'inscriptionStatus.name'
                    - property: 'payment.typePayment'
                    - property: 'trip.name'
                    - property: 'status'
                    - property: 'nbCompanion'
            form:
                title: 'Ajouter / Modifier un participant à une sortie'
                fields:
                    - user
                    - trip
                    - { property: 'nb_companion', type: 'text'}
                    - payment
                    - status
                    - inscriptionStatus
                    - comment
        Insurance:
            class: App\Entity\Insurance
            label: "Types d'assurance"
            list:
                title: "Type d'assurance"
                fields:
                    - name
                    - { property: 'price', number: '%0.02f €' }
            form:
                title: "Ajouter / Modifier un type d'assurance"
                fields:
                    - name
                    - { property: 'price', number: '%0.02f €' }
        InscriptionStatus:
            translation_domain: 'messages'
            class: App\Entity\InscriptionStatus
            label: "Statut des inscriptions"
            list:
                title: "Statut des inscriptions"
                fields:
                    - name
            form:
                title: "Ajouter / Modifier un statut"
                fields:
                    - name
        Inscription:
            translation_domain: 'messages'
            class: App\Entity\Inscription
            label: 'Inscriptions'
            list:
                title: 'Liste des inscriptions'
                fields:
                    - user
                    - inscriptionStatus
                    - status
                    - inscription_year
                    - insurance
                    - adhesionPrice
                    - { property: 'internal_procedure', template: 'vich_uploader_inscriptionPdf.html.twig', base_path: /uploads/files/users}
                    - { property: 'medical_certificate', template: 'vich_uploader_inscriptionPdf.html.twig', base_path: /uploads/files/users}
                    - { property: 'inscription_sheet', template: 'vich_uploader_inscriptionPdf.html.twig', base_path: /uploads/files/users}
                    - { property: 'image_right',  type: 'boolean' }
            search:
                fields:
                    - property: 'user.firstname'
                    - property: 'user.lastname'
                    - property: 'inscriptionStatus.name'
                    - property: 'inscriptionYear'
                    - property: 'insurance.name'
                    - property: 'adhesionPrice.name'
            form:
                title: "Ajouter / Modifier l'inscription d'un adhérent"
                fields:
                    - user
                    - inscriptionStatus
                    - status
                    - { property: 'inscription_year', type: 'text'}
                    - insurance
                    - adhesionPrice
                    - { property: 'image_right',  type: 'checkbox' }
        Document:
            translation_domain: 'messages'
            class: App\Entity\Document
            label: 'Documents'
            list:
                title: 'Documents'
                fields:
                    - name
                    - { property: 'documentFile', template: 'vich_uploader_file.html.twig', base_path: '%app.path.product_files%' }
            form:
                title: 'Modifier un document'
                fields:
                    - { property: 'documentFile', type: 'vich_file' }
            new:
                title: 'Ajouter un document'
                fields:
                    - { property: 'documentFile', type: 'vich_file' }
        AdhesionPrice:
            class: App\Entity\AdhesionPrice
            label: "Type d'adhésion"
            list:
                title: "Type d'adhésion"
                fields:
                    - name
                    - { property: 'price', number: '%0.02f €'}
            form:
                title: "Ajouter / Modifier un type d'adhésion"
                fields:
                    - name
                    - { property: 'price', number: '%0.02f €'}








