vich_uploader:
    db_driver: orm
    mappings:
        gallery_images:
            uri_prefix: '%app.path.gallery_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.gallery_images%'
