vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
#            inject_on_load:   false
#            delete_on_update: true
#            delete_on_remove: true
#    metadata:
#        auto_detection: false
#        directories:
#            - {path: '%kernel.root_dir%/vich_uploader', namespace_prefix: 'Admin'}




