vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            inject_on_load:   true
            delete_on_update: true
            delete_on_remove: true

        product_files:
            uri_prefix:         '%app.path.product_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_files%'
            inject_on_load:   true
            delete_on_update: true
            delete_on_remove: true

        image_users:
            uri_prefix:         '%app.path.image_users%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_users%'
            inject_on_load:   true
            delete_on_update: true
            delete_on_remove: true




