#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
     path: /logout
     methods: GET
_liip_imagine:
     resource: "@LiipImagineBundle/Resources/config/routing.yaml"
